mysite/ftp/urls.py
from django.contrib import admin
from .import views
from django.views.generic import TemplateView
from django.urls import include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
# from ftp import views as core_views
# from ftp.views import Add_tags

app_name = 'ftp'

urlpatterns = [
    re_path(r'^test', views.test),
    # re_path(r'^projects/anu/apply', views.personalNotice, name='personalNotice'),
    re_path(r'^projects/notices', views.personalNotice, name='personalNotice'),
    re_path(r'^projects/anu/success', TemplateView.as_view(
        template_name='ftp/ProjectsPage/anu_apply_confirm.html'), name='anu_projects_confirmation'),
    re_path(r'^projects/epfl/success', TemplateView.as_view(
        template_name='ftp/ProjectsPage/epfl_apply_confirm.html'), name='epfl_projects_confirmation'),
    re_path(r'^projects/anu', views.view_anu_projects, name='anu_projects'),
    re_path(r'^projects/new_anu', views.view_anu_2022, name='anu_projects_new'),
    re_path(r'^projects/saip/success', TemplateView.as_view(
        template_name='ftp/ProjectsPage/saip_apply_confirm.html'), name='saip_projects_confirmation'),
    re_path(r'^temp/', views.temp, name='temp'),
    re_path(r'^$', views.index, name='index'),




    re_path(r'^register/', views.register, name='register'),
    re_path(r'^dashboard_mail/$', views.dashboard_mail, name='dashboard_mail'),
    re_path(r'^login/$', views.login_user, name='login_user'),
    re_path(r'^session/$',
            TemplateView.as_view(template_name='ftp/session.html'), name='session'),
    re_path(r'^profile/$', views.view_profile, name='view_profile'),
    re_path(r'^logout_user/$', views.logout_user, name='logout_user'),
    re_path(r'^create_profile/$', views.create_profile, name='create_profile'),
    re_path(r'^resend_activation/(?P<user_id>[0-9a-f-]+)/$',
            views.resendActivation, name='resend_activation'),
    re_path(r'^password_reset/', auth_views.PasswordResetView,
            name='password_reset'),
    re_path(r'^account_activation_sent/$',
            auth_views.PasswordResetConfirmView, name='account_activation_sent'),
    re_path(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    re_path(r'^projects/$', views.view_projects, name='projects'),
    re_path(r'^project_info/$', views.project_details, name='project_info'),
    re_path(r'^apply_project/(?P<project_id>[0-9a-f-]+)/$',
            views.view_apply_project, name='view_apply_project'),
    re_path(r'^scholarships/$', views.view_scholarships, name='scholarships'),
    re_path(r'^scholarships_new/$', views.view_scholarships_new,
            name='scholarships_new'),
    re_path(r'^scholarships_new/(?P<scholarship_id>[0-9a-f-]+)/$',
            views.view_scholarship_apply, name='scholarship_apply'),
    re_path(r'^scholarships/2023/$', views.apply_scholarships_2k23,
            name='apply_scholarships_2k23'),
    re_path(r'^scholarships/gkf/$', views.apply_gkf, name='apply_gkf'),
    re_path(r'^scholarships/gkf/success/$', TemplateView.as_view(
        template_name='ftp/Scholarship/gkf_apply_confirm.html'), name='gkf_confirmation'),
    re_path(r'^scholarships/scholarships/2023/success/$', TemplateView.as_view(
        template_name='ftp/Scholarship/scholarships_2k23_apply_confirm.html'), name='scholarships_2k23_confirmation'),
    re_path(r'^scholarships/gkf/export/all/$',
            views.export_gkf, name='export_gkf'),
    re_path(r'^export_emails/$',
            views.export_emails, name='export_emails'),
    re_path(r'^scholarships/apply/(?P<scholarship_id>[0-9a-f-]+)/$',
            views.apply_scholarship, name='apply_scholarship'),
    re_path(r'^scholarships/yourscholarships/$',
            views.yourscholarships, name='yourscholarships'),
    re_path(r'^results/$', views.view_results, name='results'),
    re_path(r'^projects/(?P<project_id>[0-9a-f-]+)/$',
            views.apply_project, name='apply_project'),
    re_path(r'^applications/$', views.already_applied, name='yourapplications'),
    re_path(r'^professors/(?P<project_id>[0-9a-f-]+)/$',
            views.applied_students, name='applied_students'),
    re_path(
        r'^professors/(?P<project_id>[0-9a-f-]+)/profile/(?P<profile_id>[0-9a-f-]+)/$', views.view_frame, name='iframe'),
    re_path(r'^favorites/$', views.view_favorite, name='bookmarked'),
    re_path(r'^scholarships/yourscholarships/$',
            views.yourscholarships, name='yourscholarships'),
    re_path(r'^favorites/add_favourite/(?P<pk>[0-9a-f-]+)/$',
            views.add_favorite, name='add_favorite'),
    re_path(r'^domain_change/$', views.domain_change, name='domainchange'),
    re_path(r'^domain_reset_form/$',
            views.domain_reset_form, name='domainresetform'),
    re_path(r'^forgot-send_email/$', views.forgotpass, name='forgotpassword'),
    re_path(
        r'^forgot/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.pass_reset, name='forgottoken'),
    re_path(r'^forgot-password_reset_done/$', views.pass_reset_done,
            name='forgot_password_reset_done'),
    re_path(r'^professor_add/$', views.get_detail, name="prof_details"),
    re_path(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    re_path(r'^dashboard_projects/$',
            views.admin_projects, name='admin_projects'),
    re_path(r'^dashboard_projects/project_csv/$',
            views.project_csv, name='project_csv'),
    re_path(r'^dashboard_projects/professor_csv/$',
            views.professor_csv, name='professor_csv'),
    re_path(r'^dashboard_projects/applicants/$',
            views.applicant_profile, name='applicant_profile'),
    re_path(r'^dashboard_projects/teams/$',
            views.hult_profile, name='hult_profile'),
    re_path(r'^dashboard_projects/mail/$',
            views.applicant_mail, name='applicant_mail'),
    re_path(r'^dashboard_profiles/applicants_edit/(?P<pk>[0-9a-f-]+)/$',
            views.applicant_profile_edit.as_view(), name='applicant_profile_edit'),
    re_path(r'^dashboard_scholarship/$',
            views.admin_scholarship, name='admin_scholarship'),
    re_path(r'^dashboard_scholarship/applicants/$',
            views.scholarship_applicant_profile, name='scholarship_applicant_profile'),
    re_path(r'^dashboard_scholarship/gkf_applicants/$',
            views.gkf_scholarship_applicant_profile, name='gkf_scholarship_applicant_profile'),
    # re_path(r'^dashboard_scholarships/delete/(?P<pk>[0-9a-f-]+)/$', views.scholarship_delete,name="scholarship_delete"),
    re_path(r'^dashboard_scholarships/create/$',
            views.admin_scholarships_create, name="admin_scholarships_create"),
    re_path(r'^dashboard_scholarships/edit/(?P<pk>[0-9a-f-]+)$',
            views.ScholarshipUpdate.as_view(), name="admin_scholarships_edit"),
    re_path(r'^dashboard_scholarships/change/$',
            views.change_display_scho, name='change_display_scho'),
    # re_path(r'^dashboard_projects/export/$', views.export_project, name='admin_projects_export'),
    re_path(r'^dashboard_projects/export/(?P<pk>[0-9a-f-]+)/$',
            views.export_applied_list, name='admin_applied_list_export'),
    re_path(r'^dashboard_anu_projects/export/all/$',
            views.export_applied_anu_all_list, name='admin_applied_anu_all_list_export'),
    re_path(r'^dashboard_anu_projects/export/(?P<project_name>.+)/$',
            views.export_applied_anu_list, name='admin_applied_anu_list_export'),
    re_path(r'^dashboard_projects/scholarship_csv/$',
            views.scholarship_csv, name='scholarship_csv'),
    re_path(r'^dashboard_profiles/export/$',
            views.export_profile, name='admin_profiles_export'),
    re_path(r'^dashboard_profiles/export_topics/$',
            views.export_topics, name='admin_topics_export'),
    re_path(r'^dashboard_profiles/export_mail_ids/$',
            views.export_mail_ids, name='admin_mail_ids_export'),
    re_path(r'^dashboard_profiles/clear-search/$',
            views.clear_search, name='clear_search'),
    re_path(r'^dashboard_profiles/search/$',
            views.search_profile, name='profile_search'),
    re_path(r'^dashboard_dyuti/export/$',
            views.export_dyuti, name='admin_dyuti_export'),
    re_path(r'^dashboard_projects/edit/prereq/(?P<name>.+)/$',
            views.edit_prereq, name='admin_prereqs_edit'),
    re_path(r'^dashboard_hult/export/$',
            views.export_hult, name='admin_hult_export'),
    re_path(r'^dashboard_saip/export/$',
            views.export_saip, name='admin_saip_export'),
    re_path(r'^dashboard_profiles/$',
            views.admin_profiles, name='admin_profiles'),
    re_path(r'^dashboard_addresult/(?P<pk>[0-9a-f-]+)/$',
            views.addresult, name='admin_Addresult'),
    re_path(r'^dashboard_projects/create/$',
            views.project_create, name='admin_projects_create'),
    re_path(r'^dashboard_profiles/create/$',
            views.profile_create, name='admin_profiles_create'),
    re_path(r'^dashboard_projects/edit/(?P<pk>[0-9a-f-]+)/$',
            views.ProjectUpdate.as_view(), name='admin_projects_edit'),
    re_path(r'^dashboard_profiles/edit/(?P<pk>[0-9a-f-]+)/$',
            views.ProfileUpdate.as_view(), name='admin_profiles_edit'),
    # re_path(r'^dashboard_projects/delete/(?P<pk>[0-9a-f-]+)/$', views.project_delete, name='admin_projects_delete'),
    #re_path(r'^dashboard_profiles/delete/(?P<pk>[0-9a-f-]+)/$', views.profile_delete, name='admin_profiles_delete'),
    re_path(r'^dashboard_projects/change_display/$',
            views.project_display_change, name='change_display'),
    re_path(r'^dashboard_projects/change_prof_display/$',
            views.change_prof_display, name='change_prof_display'),
    re_path(r'^dashboard_dyuti/$', views.admin_dyuti, name='admin_dyuti'),

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ftp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/bookmarks.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Bookmarks | FTP | International Relations Cell{% endblock %}

{% block main %}
<script type="text/javascript" src="{% static 'ftp/ProjectsPage/js/modal.js' %}"></script>
<main>
    {% for p in allprojects %}
    {% if p.display %}
    <div class="projectFormContainer">
        {% if p in applieds %}
        {% for i in app %}
        {% if i.project.id == p.id %}
        <form class="projectForm" id="project-{{p.id}}">
            <i class="fa fa-close" onclick="closeForm('{{p.id}}')"></i>
            <h1>{{p.project_name}}</h1>
            <h2>{{p.university}}</h2>
            <div class="projectForm__editables">
                {% if p.special %}
                <p>Letter Of Interest:</p>
                <textarea class="projectForm__ftpLOI" type="text" disabled>{{i.Loi}}</textarea>
                {% endif %}
                <p>Statement Of Purpose:</p>
                <textarea class="projectForm__ftpSOP" type="text" disabled>{{i.sop}}</textarea>
                {% if p.multi_domain %}
                <div class="projectForm__domain">
                    Project Domain Pref. 1:&nbsp;<b>{{ i.project_domain1 }}</b>
                </div>
                <div class="projectForm__domain">
                    Project Domain Pref. 2:&nbsp;<b>{{ i.project_domain2 }}</b>
                    </select>
                </div>
                <div class="projectForm__domain">
                    Project Domain Pref. 3:&nbsp;<b>{{ i.project_domain3 }}</b>
                </div>
                {% endif %}
            </div>
            {% if i.ncv %}
            <button class="project__uploadFileBtn" style="background-color: #00506B;"
                onclick="window.open('{{ MEDIA_URL }}{{ i.ncv }}', '_blank')">Your CV for this project:
                Different</button>
            {% else %}
            <button class="project__uploadFileBtn" style="background-color: #00506B;"
                onclick="window.open('{{ MEDIA_URL }}{{ prof.cv }}', '_blank')">Your CV for this
                project: Default</button>
            {% endif %}
        </form>
        {% endif %}
        {% endfor %}
        {% else %}
        <form class="projectForm" id="project-{{p.id}}" action="{% url 'ftp:apply_project' project_id=p.id %}"
            method="POST" enctype="multipart/form-data"
            onsubmit="if(!confirm('Are you sure you want to submit? You cannot change the details later.')){return false;}">
            {% csrf_token %}
            <i class="fa fa-close" onclick="closeForm('{{p.id}}')"></i>
            <h1>{{p.project_name}}</h1>
            <h2>{{p.university}}</h2>
            <div class="projectForm__editables">
                {% if p.special %}
                <p>Letter Of Interest:</p>
                <textarea name="Loi" class="projectForm__ftpLOI"
                    placeholder="A brief essay indicating your interest in the research project and your relevant background (500 words)"
                    onkeyup="wordCountCheck(event)"></textarea>
                {% endif %}
                <p>Statement Of Purpose:</p>
                <textarea class="projectForm__ftpSOP" type="text"
                    placeholder="Write a statement of importance of the proposed research to your future in 250 words."
                    onkeyup="wordCountCheck(event)" name="sop"></textarea>
                {% if p.multi_domain %}
                <div class="projectForm__domain">
                    Select Project Domain Pref. 1
                    <select name="proj_domain1" class="form-group">
                        {% for domain in proj_domains %}
                        {% if domain.project == p %}
                        <option style="text-align: center" value="{{ domain.name }}">{{ domain.name }}
                        </option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="projectForm__domain">
                    Select Project Domain Pref. 2
                    <select name="proj_domain2" class="form-group">
                        {% for domain in proj_domains %}
                        {% if domain.project == p %}
                        <option style="text-align: center" value="{{ domain.name }}">{{ domain.name }}
                        </option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="projectForm__domain">
                    Select Project Domain Pref. 3
                    <select name="proj_domain3" class="form-group">
                        {% for domain in proj_domains %}
                        {% if domain.project == p %}
                        <option style="text-align: center" value="{{ domain.name }}">{{ domain.name }}
                        </option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
                {% endif %}
                <input type="file" class="section__uploadFileInput" accept="application/pdf"
                    onchange="changedFile(event)" name="ncv" />
                <button class=" project__uploadFileBtn" style="background-color: #00506B;" onclick="uploadFile(event)">
                    Apply with a different CV
                </button>
                <p>(optional)</p>
            </div>
            <div class=" projectForm__wordCountAlert">
                <p style="margin-bottom: 10px;">SOP word count: 0<br />LOI word count: 0</p>
                <p>SOP limit: 150-1250 words<br />{% if p.special %}LOI limit: 500 words{% endif %}</p>
            </div>
            <button class="projectForm__submitBtn projectForm__disabledBtn" onmouseenter="openWordCountAlert(event)"
                onclick="submitProjectForm(event, '')" onmouseleave="closeWordCountAlert(event)"
                onblur="closeWordCountAlert(event)">Submit</button>
        </form>
        {% endif %}
    </div>
    {% endif %}
    {% endfor %}

    <section>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="text-align: center;">{{ message
                }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <h1>Bookmarks</h1>
        <hr
            style="border: none;outline: none;height: 2px;max-width: 1000px; width: calc(100vw - 20px);background-color: #d5d5d5; margin-top: 10px;margin-bottom: 20px" />
        {% if success %}
        <h2>No Bookmarked Projects</h2>
        {% else %}
        <div class="section__projects">
            {% for project in allprojects %}
            {% if project.display %}
            <li>
                <div class="card">
                    <img src="{{project.project_image.url}}" class="card__image" alt="" />
                    <div class="card__overlay">
        
                        <div class="card__header">
                            <svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path d="M 40 80 c 22 0 40 -22 40 -40 v 40 Z"	 ></path></svg>
                            <a href="{% url 'ftp:add_favorite' pk=project.id %}"><i class="{% if project in bookmarks %}fas{% else %}far{% endif %} fa-bookmark bookmark"
                                id="book{{ project.id }}"></i></a>
                            <div class="card__header-text">
                                <h3 class="card__title">{{project.university}}</h3>
                                <!-- <span class="card__status">1 hour ago</span> -->
                            </div>
                        </div>
                        <p class="card__description">{{project.project_detail|slice:'50'}}...</p>
                        <div style="display:grid;grid-template-columns:repeat(2,1fr);margin:auto;text-align:center">
                            <a href="#"><button style="margin-bottom:10px">READ MORE</button></a>
                            <button style="margin-bottom:10px" onclick="openForm('{{project.id}}')">APPLY NOW</button>
                        </div>
                    </div>
                </div>
            </li>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
    </section>
</main>
{% endblock %}
{% block js %}
<script>
    
</script>
{% endblock %}

mysite/templates/projects.html
{% extends 'base.html' %}
{% block main %}
<script>

	
	function check(params) {
		console.log(params);
	}
</script>
<script>
	$(document).ready(


		function () {

			setCheckboxSelectLabels();

			$('.toggle-next').click(function () {
				$(this).next('.checkboxes').slideToggle(400);
			});

			$('.ckkBox').change(function () {
				if ($('.ckkBox:checked').length > 0)
					$(".reqbtn").removeClass("disabled");
				else
					$(".reqbtn").addClass("disabled");
				{% comment %} console.log($(".other:checked")); {% endcomment %}
				if ($(".other:checked").length == 1) {
					console.log("checkd");
					$(".req-input").css("display", "block");
					$(".req-input").prop('required', true);
				}
				else {
					$(".req-input").css("display", "none");
					$(".req-input").prop('required', false);
				}

				toggleCheckedAll(this);
				setCheckboxSelectLabels();
			});

		});


	function setCheckboxSelectLabels(elem) {
		var wrappers = $('.wrapper');
		$.each(wrappers, function (key, wrapper) {
			var checkboxes = $(wrapper).find('.ckkBox');
			var label = $(wrapper).find('.checkboxes').attr('id');
			var prevText = '';
			$.each(checkboxes, function (i, checkbox) {
				var button = $(wrapper).find('button');
				if ($(checkbox).prop('checked') == true) {
					var text = $(checkbox).next().html();
					var btnText = prevText + text;
					var numberOfChecked = $(wrapper).find('input.val:checkbox:checked').length;
					if (numberOfChecked >= 4) {
						btnText = numberOfChecked + ' ' + label + ' selected';
					}
					$(button).text(btnText);
					prevText = btnText + ', ';
				}
			});
		});
	}

	function toggleCheckedAll(checkbox) {
		var apply = $(checkbox).closest('.wrapper').find('.apply-selection');
		apply.fadeIn('slow');

		var val = $(checkbox).closest('.checkboxes').find('.val');
		var all = $(checkbox).closest('.checkboxes').find('.all');
		var ckkBox = $(checkbox).closest('.checkboxes').find('.ckkBox');

		if (!$(ckkBox).is(':checked')) {
			$(all).prop('checked', true);
			return;
		}

		if ($(checkbox).hasClass('all')) {
			$(val).prop('checked', false);
		} else {
			$(all).prop('checked', false);
		}
	}
</script>
<div>
	<a href="{% url 'ftp:yourapplications' %}">
		<button class="viewsApplicationsBtn" style="background: linear-gradient(135deg, #001A3B , #00506B , #007C96 , #00809B);--bs-link-hover-color: #fff;
		text-decoration: none;border: 2px solid white;position:absolute;top:80px;right:10px;width:200px;height:50px;color:white;font-size:15px">Go to
			applied Projects <i class="fas fa-arrow-right" style="padding-left: 5px"></i></button>
	</a>
	{% for p in allprojects %}
	{% if p.display %}
	<div class="projectFormContainer">
		<form class="projectForm" id="project-{{p.id}}" action="{% url 'ftp:apply_project' project_id=p.id %}"
			method="POST" enctype="multipart/form-data"
			onsubmit="if(!confirm('Are you sure you want to submit? You cannot change the details later.')){return false;}">
			{% csrf_token %}
			<i class="fa fa-close" onclick="closeForm('{{p.id}}')"></i>
			<h1>{{p.project_name}}</h1>
			<h2>{{p.university}}</h2>
			<div class="projectForm__editables">
				{% if p.special %}
				<p>Letter Of Interest:</p>
				<textarea name="Loi" class="projectForm__ftpLOI"
					placeholder="A brief essay indicating your interest in the research project and your relevant background (500 words)"
					onkeyup="wordCountCheck(event)"></textarea>
				{% endif %}
				<p>Statement Of Purpose:</p>
				<textarea class="projectForm__ftpSOP" type="text"
					placeholder="Write a statement of importance of the proposed research to your future in 150 to 200 words."
					onkeyup="wordCountCheck(event)" name="sop"></textarea>
				{% if p.multi_domain %}
				<div class="projectForm__domain">
					Select Project Domain Pref. 1
					<select name="proj_domain1" class="form-group">
						{% for domain in proj_domains %}
						{% if domain.project == p %}
						<option style="text-align: center" value="{{ domain.name }}">{{ domain.name }}
						</option>
						{% endif %}
						{% endfor %}
					</select>
				</div>
				<div class="projectForm__domain">
					Select Project Domain Pref. 2
					<select name="proj_domain2" class="form-group">
						{% for domain in proj_domains %}
						{% if domain.project == p %}
						<option style="text-align: center" value="{{ domain.name }}">{{ domain.name }}
						</option>
						{% endif %}
						{% endfor %}
					</select>
				</div>
				<div class="projectForm__domain">
					Select Project Domain Pref. 3
					<select name="proj_domain3" class="form-group">
						{% for domain in proj_domains %}
						{% if domain.project == p %}
						<option style="text-align: center" value="{{ domain.name }}">{{ domain.name }}
						</option>
						{% endif %}
						{% endfor %}
					</select>
				</div>
				{% endif %}
				<input type="file" class="section__uploadFileInput" accept="application/pdf"
					onchange="changedFile(event)" name="ncv" />
				<button class=" project__uploadFileBtn" style="background-color: #00506B;" onclick="uploadFile(event)">
					Apply with a different CV
				</button>
				<p>(optional)</p>
			</div>
			<div class=" projectForm__wordCountAlert">
				<p style="margin-bottom: 10px;">SOP word count: 0<br />LOI word count: 0</p>
				<p>SOP limit: 150-200 words<br />{% if p.special %}LOI limit: 500 words{% endif %}</p>
			</div>
			<button class="projectForm__submitBtn projectForm__disabledBtn" onmouseenter="openWordCountAlert(event)"
				onclick="submitProjectForm(event, '')" onmouseleave="closeWordCountAlert(event)"
				onblur="closeWordCountAlert(event)">Submit</button>
		</form>
	</div>
	{% endif %}
	{% endfor %}
</div>
<h1 style="text-align: center;margin-top:120px">Projects</h1>
<ul class="cards">
	
	{% for project in allprojects %}
	{% if project.display %}
	<li class="project_cards">
		<div class="card">
			<img src="{{project.project_image.url}}" class="card__image" alt="" />
			<div class="card__overlay">

				<div class="card__header">
					<svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path d="M 40 80 c 22 0 40 -22 40 -40 v 40 Z"	 ></path></svg>
					<a href="{% url 'ftp:add_favorite' pk=project.id %}"><i class="{% if project in bookmarks %}fas{% else %}far{% endif %} fa-bookmark bookmark"
						id="book{{ project.id }}"></i></a>
					<div class="card__header-text">
						<h3 class="card__title">{{project.university}}</h3>
						<!-- <span class="card__status">1 hour ago</span> -->
					</div>
				</div>
				<p class="card__description">{{project.project_detail|slice:'50'}}...</p>
				<div style="display:grid;grid-template-columns:repeat(2,1fr);margin:auto;text-align:center">
					<a href="#"><button style="margin-bottom:10px">READ MORE</button></a>
					<button style="margin-bottom:10px" onclick="openForm('{{project.id}}')">APPLY NOW</button>
				</div>
			</div>
		</div>
	</li>
	{% endif %}
	{% endfor %}
</ul>
<script src="https://code.jquery.com/jquery-3.6.1.min.js"
	integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
	crossorigin="anonymous"></script>
{% endblock %}